name: Run generated tests

on:
  push:
    branches: [ main ]

jobs:
  buildandroid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-java@v1
      with:
        java-version: '15'

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.0'
        channel: stable

    - run: flutter pub get

    - run: flutter test